# ASTRO >>> https://github.com/dsutphin/bsidesroanoke.github.io
title: "@Artistan Designs + Engineering"
description: Bookmark this to keep an eye on my project updates!
theme: minima

twitter_username: artistan
github_username:  artistan

# minima:
#   skin: dark

# # Build settings
# remote_theme: jekyll/minima@2863624
# plugins:
#   - jekyll-remote-theme

show_excerpts: true
