# https://github.com/dsutphin/bsidesroanoke.github.io

theme: minima
title: "@Artistan Designs + Engineering"
description: Bookmark this to keep an eye on my project updates!
remote_theme: "jekyll/minima@1e8a445"
email: webmaster@artistan.org

twitter_username: artistan
github_username:  artistan

minima:
  skin: solarized-dark

  
# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .github
  - .gitignore
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
